const fs = require('fs');
const path = require('path');
const { buildApiUrls } = require('./ApiURL.js');

const URL_SERVICE = process.env.REACT_APP_API_ENDPOINT;

if (!URL_SERVICE) {
    console.error('❌ REACT_APP_API_ENDPOINT tidak ditemukan di .env');
    process.exit(1);
}

function encodeTree(obj) {
    const result = {};
    for (const key in obj) {
        const v = obj[key];
        if (typeof v === 'string') {
            result[key] = Buffer.from(v, 'utf8').toString('base64');
        } else if (v !== null && typeof v === 'object') {
            result[key] = encodeTree(v);
        } else {
            result[key] = v;
        }
    }
    return result;
}

const apiUrls = buildApiUrls(URL_SERVICE);
const encoded = encodeTree(apiUrls);

const output = `// AUTO-GENERATED by CompileURL.js — NO EDIT MANUALLY
// Regenerate: node CompileURL.js
// Generated at: ${new Date().toISOString()}

export const apiUrls = ${JSON.stringify(encoded, null, 4)};
`;

const outPath = path.join(__dirname, 'EncodedURLs.js');
fs.writeFileSync(outPath, output, 'utf8');

let count = 0;
const countLeaves = (o) => {
    for (const k in o) {
        if (typeof o[k] === 'string') count++;
        else if (typeof o[k] === 'object') countLeaves(o[k]);
    }
};
countLeaves(encoded);